### PR TITLE
Lower case the UI output for hover behaviour.

### PR DESCRIPTION
**Pull request by Ictinus**
main.js -> configSimaElements() is looking for lower case values.

### CODE REVIEW

**Comment by computermacgyver** [comment]
Great catch. Thanks for creating the pull request. I'll roll this into a release I hope to get out next week.

**Comment by Ictinus** [comment]
Very happy to help. I'd love to offer a suggested improvement to the dimming in main.js (dim with delay/timeout), but how do you work with (apply edits) to the main.js in the zipped resource? I've not used NetBeans before.

**Comment by computermacgyver** [comment]
My first project with netbeans as well. The zip is a cleaned up version of the network folder in this project:
https://github.com/oxfordinternetinstitute/InteractiveVis/tree/master/network
So feel free to branch that and apply any changes to the network/js/main.js file (or others).

Thanks!

**Comment by Ictinus** [comment]
Done, cheers.

**Pull request merged**
